
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gdlup
 */
public class VentanaTratamientoCatalogo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTratamientoCatalogo
     */
    public VentanaTratamientoCatalogo() {
        initComponents();
        m = (DefaultTableModel) tblTratamientos.getModel();
        leerTratamientos();
        id++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTratamientos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Catalogo de tratamientos");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblTratamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Medicinas", "Fecha", "Duracion"
            }
        ));
        tblTratamientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTratamientosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTratamientos);

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnBuscar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(334, 334, 334)
                                .addComponent(btnEliminar)
                                .addGap(17, 17, 17)
                                .addComponent(btnEditar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if (txtSearch.getText().equals("")) {
            leerTratamientos();
            return;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyPressed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        if (txtSearch.getText().equals("")) {
            leerTratamientos();
            return;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtSearch.getText().equals("")) {
            leerTratamientos();
            return;
        } else {
            int id = Integer.parseInt(txtSearch.getText());

            int tratamientoPOS = buscaTratamiento(id, T);

            if (tratamientoPOS == -1) {
                showMessageDialog(this, "Registro no encontrado");

            } else {
                Tratamiento tratamientoEncontrado = T[tratamientoPOS];
                m.setRowCount(0);

                Object R[] = new Object[4];
                //ciclo que si se cumple, manda a agregar a la tabla para cuando inicie el programa de nuevo

                R[0] = tratamientoEncontrado.getId();
                R[1] = tratamientoEncontrado.getMedicinas();
                R[2] = tratamientoEncontrado.getFecha();
                R[3] = tratamientoEncontrado.getDuracion();
                
                id = tratamientoEncontrado.getId();
                m.addRow(R);
                t++;
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblTratamientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTratamientosMouseClicked
        userSelectedID = obtenerIdTratamientoSeleccionado();
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTratamientosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int tratamientoEDITPOS = buscaTratamiento(userSelectedID, T);

        if (showConfirmDialog(this, "Se borrará el renglón, ¿proceder?") == 0) {
            m.removeRow(tratamientoEDITPOS); // pos, pues es la posicion de la que se habla, se borra en la tabla
            eliminarTratamiento(tratamientoEDITPOS);
            guardarArray(); //para guardarlo en el archivo
            //txtID.setText("");

            btnEditar.setEnabled(false);
            btnEliminar.setEnabled(false);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void guardarArray() {

        try {
            //se abre el flujo y se manda el metodo para guardar
            FileOutputStream flujoBytes = new FileOutputStream("Tratamientos.obj");
            fcs = new ObjectOutputStream(flujoBytes);
            fcs.writeObject(T);
            fcs.flush();
        } catch (IOException ex) {
            showMessageDialog(this, "Error");
        }

    }

    private void leerTratamientos() {
        try {
            FileInputStream flujoBytes = new FileInputStream("Tratamientos.obj"); //flujo de Bytes
            fce = new ObjectInputStream(flujoBytes); //flujo de objetos
            T = (Tratamiento[]) fce.readObject();
            Object R[] = new Object[4];
            m.setRowCount(0);

            //ciclo que si se cumple, manda a agregar a la tabla para cuando inicie el programa de nuevo
            for (int i = 0; i < T.length; i++) {
                if (T[i] == null) {
                    return; //si el renglon que quiere agregar está vacío, no lo agregará y no marcará error
                }

                R[0] = T[i].getId();
                R[1] = T[i].getMedicinas();
                R[2] = T[i].getFecha();
                R[3] = T[i].getDuracion();
               
                id = T[i].getId();
                m.addRow(R);
                t++;
            }

        } catch (FileNotFoundException ex) {
            showMessageDialog(this, "Error el archivo no se encontro");
        } catch (IOException ex) {
            showMessageDialog(this, "Error");
        } catch (ClassNotFoundException ex) {
            showMessageDialog(this, "Error");
        }
    }

    public int buscaTratamiento(int ca, Tratamiento A[]) {
        for (int i = 0; i < A.length; i++) {
            if(A[i]== null){
                return -1;
            }
            if (ca == T[i].getId()) {
                if (T[i] == null) {
                    return -1; //si el renglon que quiere agregar está vacío, no lo agregará y no marcará error
                }
                return i; //Return el arreglo en esa posición
            }//Para que compare id (parámetro) con id del arreglo
        }
        return -1; //Por si no los encontró

    }

    private int obtenerIdTratamientoSeleccionado() {
        // Obtener el índice de la fila seleccionada en la tabla
        int rowIndex = tblTratamientos.getSelectedRow();

        // Verificar si hay una fila seleccionada
        if (rowIndex != -1) {
            // Obtener el valor del ID del cliente en la columna 0 (primera columna)
            int idTratamiento = (int) tblTratamientos.getValueAt(rowIndex, 0);

            btnEditar.setEnabled(true);
            btnEliminar.setEnabled(true);
            // retornar el ID del cliente en un mensaje
            return idTratamiento;
        } else {
            return -1;
        }
    }

    public void eliminarTratamiento(int posicion) {

        // Copiar los elementos antes de la posición
        System.arraycopy(T, 0, T, 0, posicion);

        // Copiar los elementos después de la posición
        System.arraycopy(T, posicion + 1, T, posicion, T.length - posicion - 1);

        // Asignar null al último elemento
        T[T.length - 1] = null;

    }

    private void llenaTabla() {
        for (int i = 0; i < t; i++) {
            //if
            m.setValueAt(T[i].getId(), i, 0);
            m.setValueAt(T[i].getMedicinas(), i, 1);
            m.setValueAt(T[i].getFecha(), i, 2);
            m.setValueAt(T[i].getDuracion(), i, 3);
            

        }

    }

    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        int tratamientoEDITPOS = buscaTratamiento(userSelectedID, T);

        VentanaTratamientoActualizar frame1 = new VentanaTratamientoActualizar(T[tratamientoEDITPOS]);

        frame1.setVisible(true);

        // Agregar un WindowListener a la ventana de actualización
        frame1.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                
                System.out.println("La ventana se cerró. Ejecutando código...");
                

                T[tratamientoEDITPOS] = frame1.T;
                guardarArray();
                leerTratamientos();
            }
        });
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTratamientoCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTratamientoCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTratamientoCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTratamientoCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTratamientoCatalogo().setVisible(true);
            }
        });
    }
    private Tratamiento T[] = new Tratamiento[30];
    private int t, id;
    private DefaultTableModel m;
    private int userSelectedID;
    private ObjectOutputStream fcs; // flujo de objetos de escritura
    private ObjectInputStream fce;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTratamientos;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
